development:
  adapter: postgresql
  encoding: unicode
  database: property_service_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: property_service_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: property_service_production
  pool: 5
  username: postgres
  password: